Develop margo
Wowtika/WordPress pull request #49
Opened 2024-10-15 20:44 UTC by MargaritaBraun

Fixes #41

2024-10-15 20:48 UTC, NikitaKalabin requested changes

2024-10-15 20:48 UTC, NikitaKalabin commented on friction-master/assets/js/app.js
> +        '<a href="/product?part_id=' + nameCategory + '">Compare rulers</a>';
Compare rulers странный перевод, учитывая, что у нас product lines фильтр было бы логичнее

2024-10-15 22:17 UTC, kostanchika approved these changes

2024-10-16 08:09 UTC, MargaritaBraun commented on friction-master/assets/js/app.js
> +        '<a href="/product?part_id=' + nameCategory + '">Compare rulers</a>';
исправлено

2024-10-16 08:11 UTC, NikitaKalabin approved these changes

2024-10-16 08:12 UTC, kostanchika approved these changes

2024-10-16 08:14 UTC, merged